/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_rongcloud_rtc_resampler_AudioResampler */
#include <android/log.h>
#ifndef _Included_cn_rongcloud_rtc_resampler_AudioResampler
#define _Included_cn_rongcloud_rtc_resampler_AudioResampler

#include "audio_resampler.h"
using namespace audio_mixer;
#ifdef __cplusplus
extern "C" {
#endif
#define LOGI(FORMAT, ...) __android_log_print(ANDROID_LOG_INFO,"Resampler_C",FORMAT,##__VA_ARGS__);
#define LOGE(FORMAT, ...) __android_log_print(ANDROID_LOG_ERROR,"Resampler_C",FORMAT,##__VA_ARGS__);

/*
 * Class:     cn_rongcloud_rtc_resampler_AudioResampler
 * Method:    n_initAudioResamper
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_cn_rongcloud_rtc_resampler_AudioResampler_n_1initAudioResamper
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     cn_rongcloud_rtc_resampler_AudioResampler
 * Method:    n_resample
 * Signature: ([BI)Lcn/rongcloud/rtc/resampler/AudioBuffer;
 */
JNIEXPORT jbyteArray JNICALL Java_cn_rongcloud_rtc_resampler_AudioResampler_n_1resample
  (JNIEnv *, jobject, jbyteArray,jint );

#ifdef __cplusplus
}
#endif
#endif
